CREATE TABLE proveedor (
    ID 			    INT	NOT NULL AUTO_INCREMENT,
    NOMBRE 		    VARCHAR(200)	 NOT NULL,
	DIRECCION       VARCHAR(300)     NOT NULL,
	TELEFONO        VARCHAR(50)     NOT NULL,
    EMAIL           VARCHAR(50)     NOT NULL,
	PRIMARY KEY (ID)
);

CREATE INDEX IDX_PROVEEDOR_ID ON proveedor (ID);

